#!/bin/bash
#Script de finalización del streaming de video
PID=$(pstree -s -p | grep -P -o 'lxterminal\([0-9]+\)' | grep -P -o '[0-9]+') #Seleccionamos el PID del proceso abierto en lxterminal
echo  Matando terminal con PID $PID
kill -9 $PID #Matamos el proceso con la opción 9